import Head from "next/head";
import Image from "next/image";
import Main from "../containers/MainHome";
import Button from "../components/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Button link="/carousel" color="#03e9f4" />
      </Main>
    </div>
  );
}
